// Generated by scripts/update-bank-codes.ts – do not edit.
// Source: ČNB, Číselník kódů platebního styku v České republice (ČKPS), verze 255, platný od 2026-10-01,
// https://www.cnb.cz/cs/platebni-styk/.galleries/ucty_kody_bank/download/kody_bank_CR.csv, staženo 2026-10-08.
// Legal basis: vyhláška č. 169/2011 Sb., § 6 odst. 2 (docs/rules/bankAccount.md section 8).
/** Kódy platebního styku (bank codes) of ČKPS version 255, ascending, separated by single spaces. */
export const BANK_CODES = '0100 0300 0600 0710 0800 2010 2060 2070 2100 2200 2220 2250 2600 2700 3030 3060 3500 4300 5500 5800 6000 6200 6210 6300 6363 6600 6700 6800 7910 7950 7960 7970 7990 8030 8040 8060 8090 8150 8198 8220 8250 8255 8265 8500 8610 8620 8660';
