// Regenerates src/bankAccount/bankCodes.ts from the ČNB list of bank codes (ČKPS).
// Contract: docs/rules/bankAccount.md section 8.4. Run manually (`npm run update:bank-codes`), never in CI.
// Usage: node scripts/update-bank-codes.ts [--version <N> --valid-from <YYYY-MM-DD>]
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { parseArgs } from 'node:util';

const CSV_URL = 'https://www.cnb.cz/cs/platebni-styk/.galleries/ucty_kody_bank/download/kody_bank_CR.csv';
const PAGE_URL = 'https://www.cnb.cz/cs/platebni-styk/ucty-kody-bank/';
const OUTPUT = new URL('../src/bankAccount/bankCodes.ts', import.meta.url);
const HEADER = 'Kód platebního styku;Poskytovatel platebních služeb;BIC kód (SWIFT);Systém CERTIS';
const MIN_ROWS = 30;
// "Číselník 255 platný od 1. 10. 2026" on the landing page, after stripping the HTML tags.
const VERSION_TEXT = /Číselník\s+(\d+)\s+platný\s+od\s+(\d{1,2})\.\s*(\d{1,2})\.\s*(\d{4})/g;

interface Edition {
  readonly version: string;
  readonly validFrom: string;
}

async function download(url: string): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`GET ${url} failed: ${String(response.status)} ${response.statusText}`);
  }
  return response.text();
}

/** Bank codes of the CSV, ascending; throws on any deviation from the documented format. */
function parseCodes(csv: string): string[] {
  const lines = csv
    .replace(/^\uFEFF/, '')
    .split(/\r?\n/)
    .filter((line) => line.trim() !== '');
  if (lines[0] !== HEADER) {
    throw new Error(`Unexpected CSV header: ${String(lines[0])}`);
  }
  const codes = lines.slice(1).map((line, index) => {
    const fields = line.split(';');
    const code = fields[0] ?? '';
    if (fields.length !== 4 || !/^[0-9]{4}$/.test(code)) {
      throw new Error(`Bad CSV row ${String(index + 2)}: ${line}`);
    }
    return code;
  });
  if (new Set(codes).size !== codes.length) {
    throw new Error('Duplicate bank codes in the CSV');
  }
  if (codes.length < MIN_ROWS) {
    throw new Error(`Only ${String(codes.length)} bank codes, expected at least ${String(MIN_ROWS)}`);
  }
  return codes.sort();
}

/** The newest edition named on the landing page. */
function parseEdition(html: string): Edition | undefined {
  const text = html.replace(/<[^>]*>/g, ' ');
  let newest: Edition | undefined;
  for (const [, version = '', day = '', month = '', year = ''] of text.matchAll(VERSION_TEXT)) {
    if (newest === undefined || Number(version) > Number(newest.version)) {
      newest = { version, validFrom: `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}` };
    }
  }
  return newest;
}

async function edition(): Promise<Edition> {
  const { values } = parseArgs({ options: { version: { type: 'string' }, 'valid-from': { type: 'string' } } });
  const validFrom = values['valid-from'];
  if (values.version !== undefined && validFrom !== undefined) {
    return { version: values.version, validFrom };
  }
  const found = parseEdition(await download(PAGE_URL));
  if (found === undefined) {
    throw new Error('Version not found on the ČNB page; pass --version <N> --valid-from <YYYY-MM-DD>');
  }
  return found;
}

/** The generated module in the exact shape of docs/rules/bankAccount.md section 8.2. */
function render(codes: readonly string[], { version, validFrom }: Edition, downloaded: string): string {
  return [
    '// Generated by scripts/update-bank-codes.ts – do not edit.',
    `// Source: ČNB, Číselník kódů platebního styku v České republice (ČKPS), verze ${version}, platný od ${validFrom},`,
    `// ${CSV_URL}, staženo ${downloaded}.`,
    '// Legal basis: vyhláška č. 169/2011 Sb., § 6 odst. 2 (docs/rules/bankAccount.md section 8).',
    `/** Kódy platebního styku (bank codes) of ČKPS version ${version}, ascending, separated by single spaces. */`,
    `export const BANK_CODES = '${codes.join(' ')}';`,
    '',
  ].join('\n');
}

function previousCodes(): string[] {
  if (!existsSync(OUTPUT)) {
    return [];
  }
  return /BANK_CODES =\s*'([0-9 ]*)'/.exec(readFileSync(OUTPUT, 'utf8'))?.[1]?.split(' ') ?? [];
}

async function main(): Promise<void> {
  const codes = parseCodes(await download(CSV_URL));
  const current = await edition();
  const before = previousCodes();
  const downloaded = new Date().toISOString().slice(0, 10);
  writeFileSync(OUTPUT, render(codes, current, downloaded));
  const added = codes.filter((code) => !before.includes(code));
  const removed = before.filter((code) => !codes.includes(code));
  process.stdout.write(
    `ČKPS ${current.version} (valid from ${current.validFrom}): ${String(codes.length)} codes\n` +
      `added: ${added.join(' ') || '–'}\nremoved: ${removed.join(' ') || '–'}\n`,
  );
}

await main();
